# AetherPDF Backend - Python Document Transmutation Server
import os
import uuid
from flask import Flask, request, send_file, jsonify
from flask_cors import CORS

# Import modular converters
from pdf_to_docx import pdf_to_docx
from pdf_to_pptx import pdf_to_pptx
from pdf_to_xlsx import pdf_to_xlsx
from docx_to_pdf import docx_to_pdf
from pptx_to_pdf import pptx_to_pdf
from xlsx_to_pdf import xlsx_to_pdf

app = Flask(__name__)
CORS(app)

TEMP_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'temp')
os.makedirs(TEMP_DIR, exist_ok=True)


@app.route('/convert', methods=['POST'])
def convert_file():
    if 'file' not in request.files or 'mode' not in request.form:
        return jsonify({"error": "Missing file or mode parameters"}), 400
        
    uploaded_file = request.files['file']
    mode = request.form['mode']
    
    if uploaded_file.filename == '':
        return jsonify({"error": "No file selected"}), 400
        
    # Generate unique filenames to prevent conflicts
    task_id = str(uuid.uuid4())
    filename = uploaded_file.filename
    ext = filename.split('.')[-1].lower()
    
    src_path = os.path.join(TEMP_DIR, f"{task_id}.{ext}")
    dest_ext = 'pdf' if 'to-pdf' in mode else ('docx' if 'to-doc' in mode else ('pptx' if 'to-ppt' in mode else 'xlsx'))
    dest_path = os.path.join(TEMP_DIR, f"{task_id}_out.{dest_ext}")
    
    # Save input file
    uploaded_file.save(src_path)
    
    try:
        if mode == 'pdf-to-doc':
            pdf_to_docx(src_path, dest_path)
        elif mode == 'pdf-to-ppt':
            pdf_to_pptx(src_path, dest_path)
        elif mode == 'pdf-to-sheets':
            pdf_to_xlsx(src_path, dest_path)
        elif mode == 'doc-to-pdf':
            docx_to_pdf(src_path, dest_path)
        elif mode == 'ppt-to-pdf':
            pptx_to_pdf(src_path, dest_path)
        elif mode == 'sheets-to-pdf':
            xlsx_to_pdf(src_path, dest_path)
        else:
            return jsonify({"error": f"Invalid conversion mode: {mode}"}), 400
            
        if not os.path.exists(dest_path):
            raise Exception("Output file was not generated by conversion module.")
            
        # Return converted file
        return send_file(
            dest_path,
            as_attachment=True,
            download_name=f"{filename.rsplit('.', 1)[0]}_converted.{dest_ext}"
        )
        
    except Exception as e:
        print(f"Error during conversion: {str(e)}")
        return jsonify({"error": str(e)}), 500
        
    finally:
        # Cleanup temp files
        try:
            if os.path.exists(src_path):
                os.remove(src_path)
            if os.path.exists(dest_path):
                os.remove(dest_path)
        except Exception as cleanup_err:
            print(f"Failed to delete temp files: {cleanup_err}")

if __name__ == '__main__':
    # Binding to 0.0.0.0 is necessary for running inside Docker
    port = int(os.environ.get("PORT", 5000))
    print(f"AetherPDF Python backend listening on http://0.0.0.0:{port}...")
    app.run(host="0.0.0.0", port=port, debug=False)
